### ISSUE TITLE
Cant install?

### ISSUE THREAD

**Issue by LeroyNoel** [sammothxc/ch552g-macropad-tool#1]
It might just be me who is being stupid,   but following ch57x install guide is not working. 

Using cargo install ch552g-macropad-tool prints error: could not find `ch552g-macropad-tool` in registry `crates-io` with version `*`

Am i missing something?

**Comment by sammothxc** [comment]
Let me try and reproduce the error, I haven't tried installing it for a while and the setup may have changed

**Comment by sammothxc** [comment]
I see what went wrong, I worded the README so that it sounds like there are installation steps that you need to follow. In reality, all you need to do is clone this repo and use the precompiled binary `ch552g-macropad-tool`.

I am going to update the README; you try the above steps and see if the precompiled binary works for you.

**Comment by LeroyNoel** [comment]
Thank you, but i still might be stupid. When i run ch552g-keyboard-tool validate < test.yaml it prints ch552g-keyboard-tool: command not found

**Comment by sammothxc** [comment]
Depending on your OS these instructions may vary but this will work for most Linux/Unix based systems. First make sure you are actually in the cloned GitHub repository and then make sure the binary is executable by running `chmod +x ./ch552g-macropad-tool`. Since the this binary is a program and not a command, you need to execute it with the prefix `./` so in this case you'd use `./ch552g-macropad-tool validate < test.yaml`

**Comment by LeroyNoel** [comment]
Thank you man.
